/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Achats: () => import('#controllers/achats_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Fournisseurs: () => import('#controllers/fournisseurs_controller'),
  Lots: () => import('#controllers/lots_controller'),
  Medicaments: () => import('#controllers/medicaments_controller'),
  Profiles: () => import('#controllers/profiles_controller'),
  Session: () => import('#controllers/session_controller'),
  Users: () => import('#controllers/users_controller'),
  Ventes: () => import('#controllers/ventes_controller'),
}
