/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AchatDetailSchema extends BaseModel {
  static $columns = ['achatId', 'id', 'lotId', 'prixUnitaire', 'quantite', 'sousTotal'] as const
  $columns = AchatDetailSchema.$columns
  @column()
  declare achatId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lotId: string
  @column()
  declare prixUnitaire: number
  @column()
  declare quantite: number
  @column()
  declare sousTotal: number
}

export class AchatSchema extends BaseModel {
  static $columns = ['createdAt', 'dateAchat', 'fournisseurId', 'id', 'montantTotal', 'numeroAchat', 'userId'] as const
  $columns = AchatSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateAchat: DateTime
  @column()
  declare fournisseurId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare montantTotal: number
  @column()
  declare numeroAchat: string
  @column()
  declare userId: string
}

export class CategorySchema extends BaseModel {
  static $columns = ['description', 'id', 'nom'] as const
  $columns = CategorySchema.$columns
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nom: string
}

export class FournisseurSchema extends BaseModel {
  static $columns = ['adresse', 'createdAt', 'email', 'id', 'nom', 'telephone', 'updatedAt'] as const
  $columns = FournisseurSchema.$columns
  @column()
  declare adresse: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nom: string
  @column()
  declare telephone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LotSchema extends BaseModel {
  static $columns = ['createdAt', 'dateExpiration', 'dateReception', 'fournisseurId', 'id', 'medicamentId', 'numeroLot', 'prixAchat', 'quantite', 'updatedAt'] as const
  $columns = LotSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateExpiration: DateTime
  @column.date()
  declare dateReception: DateTime
  @column()
  declare fournisseurId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare medicamentId: string
  @column()
  declare numeroLot: string
  @column()
  declare prixAchat: number
  @column()
  declare quantite: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MedicamentSchema extends BaseModel {
  static $columns = ['categorieId', 'createdAt', 'description', 'id', 'nom', 'prixVente', 'seuilAlerte', 'updatedAt'] as const
  $columns = MedicamentSchema.$columns
  @column()
  declare categorieId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nom: string
  @column()
  declare prixVente: number
  @column()
  declare seuilAlerte: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'nom', 'password', 'prenom', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nom: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare prenom: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VenteDetailSchema extends BaseModel {
  static $columns = ['id', 'lotId', 'prixUnitaire', 'quantite', 'sousTotal', 'venteId'] as const
  $columns = VenteDetailSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lotId: string
  @column()
  declare prixUnitaire: number
  @column()
  declare quantite: number
  @column()
  declare sousTotal: number
  @column()
  declare venteId: string
}

export class VenteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'montantTotal', 'numeroVente', 'userId'] as const
  $columns = VenteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare montantTotal: number
  @column()
  declare numeroVente: string
  @column()
  declare userId: string
}
